language: java

jdk:
  - openjdk11

addons:
  apt:
    packages:
      - libxml2-utils
services:
  - docker      
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm

#env:
  # Use these to trigger a release. You can also uncomment them in a custom config that you can
  # pass to the manual build trigger (in the web interface).
  # Note that these two cannot go into multiple lines, else Travis interprets them as multiple builds
  # This also requires that you define GIT_USER and GIT_PASSWORD, typically in the Travis settings for 
  # your repo.  
  # - NEW_RELEASE_VER='1.0' NEW_SNAPSHOT_VER='1.0-SNAPSHOT'
  
  # If these additional version-related vars are not set, they'll be set to $NEW_RELEASE_VER
  # - NEW_RELEASE_VER='1.0' NEW_SNAPSHOT_VER='1.0-SNAPSHOT' GIT_RELEASE_TAG='1.0' DOCKER_RELEASE_TAG = '1.0'
       
install:
  - export PATH="/usr/local/bin:$PATH"
  - npm config set unsafe-perm true
  - npm install bower gulp -g
  # Downgrades Node.js, due to lib clash (https://github.com/Rothamsted/knetminer/issues/432)
  # TODO: remove after the mentioned issue is fixed.
  - npm install -g n
  - npath=$(which n) # we need this, cause the installation is somewhere in $HOME and 'n' needs sudo
  - sudo $npath 11.15.0
  # The common settings file used to build with Travis
  # Beware that, because of this, this file is listed in .gitignore (Travis fails without).
  - wget https://raw.githubusercontent.com/Rothamsted/knetminer-common/master/travis/maven-settings.xml
      
script:
  ./travis-build.sh
  
branches:
  only:
  - master
  - 202006_jdk11

